"""Initial migration

Revision ID: 0089bf4129d5
Revises: 
Create Date: 2025-05-08 16:49:31.541312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0089bf4129d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('edit_type', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('before_value', sa.LargeBinary(), nullable=True),
    sa.Column('after_value', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('magic_number', sa.Integer(), nullable=False),
    sa.Column('cpu_type', sa.Integer(), nullable=False),
    sa.Column('cpu_subtype', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Integer(), nullable=False),
    sa.Column('ncmds', sa.Integer(), nullable=False),
    sa.Column('sizeofcmds', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('segname', sa.String(length=16), nullable=False),
    sa.Column('vmaddr', sa.BigInteger(), nullable=False),
    sa.Column('vmsize', sa.BigInteger(), nullable=False),
    sa.Column('fileoff', sa.BigInteger(), nullable=False),
    sa.Column('filesize', sa.BigInteger(), nullable=False),
    sa.Column('maxprot', sa.Integer(), nullable=False),
    sa.Column('initprot', sa.Integer(), nullable=False),
    sa.Column('nsects', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('cmd_type', sa.Integer(), nullable=False),
    sa.Column('cmd_size', sa.Integer(), nullable=False),
    sa.Column('cmd_offset', sa.Integer(), nullable=False),
    sa.Column('cmd_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('sectname', sa.String(length=16), nullable=False),
    sa.Column('segname', sa.String(length=16), nullable=False),
    sa.Column('addr', sa.BigInteger(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('align', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('load_commands')
    op.drop_table('segments')
    op.drop_table('headers')
    op.drop_table('edit_history')
    op.drop_table('files')
    # ### end Alembic commands ###
