"""Add file_type and architecture fields to files table

Revision ID: 67a8722844d1
Revises: a48ef93bcdef
Create Date: 2025-05-08 17:46:25.062699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a8722844d1'
down_revision = 'a48ef93bcdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cross_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset', sa.BigInteger(), nullable=True))
        batch_op.alter_column('reference_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('address')

    with op.batch_alter_table('dynamic_symbol_tables', schema=None) as batch_op:
        batch_op.alter_column('indirectsymoff',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nindirectsyms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('nextrel')
        batch_op.drop_column('locreloff')
        batch_op.drop_column('modtaboff')
        batch_op.drop_column('nlocrel')
        batch_op.drop_column('cmdsize')
        batch_op.drop_column('cmd')
        batch_op.drop_column('ntoc')
        batch_op.drop_column('tocoff')
        batch_op.drop_column('nmodtab')
        batch_op.drop_column('extrefsymoff')
        batch_op.drop_column('extreloff')
        batch_op.drop_column('nextrefsyms')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('architecture', sa.String(length=50), nullable=True))

    with op.batch_alter_table('symbol_tables', schema=None) as batch_op:
        batch_op.drop_column('cmdsize')
        batch_op.drop_column('cmd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symbol_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cmd', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cmdsize', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('architecture')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('dynamic_symbol_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nextrefsyms', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('extreloff', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('extrefsymoff', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nmodtab', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tocoff', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('ntoc', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cmd', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cmdsize', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nlocrel', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('modtaboff', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('locreloff', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nextrel', sa.INTEGER(), nullable=False))
        batch_op.alter_column('nindirectsyms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('indirectsymoff',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cross_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.BIGINT(), nullable=True))
        batch_op.alter_column('reference_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('offset')

    # ### end Alembic commands ###
